rango/urls.py
from django.conf.urls import url, patterns

from rango import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^search/$', views.search, name='search'),
    url(r'^register/$', views.register, name='register'),
    url(r'^restricted/$', views.restricted, name='restricted'),
    url(r'^add_category/$', views.add_category, name='add_category'),
    url(r'^category/(?P<category_name_url>\w+)/$', views.category, name='category'),
    url(r'^category/(?P<category_name_url>\w+)/add_page/$', views.add_page, name='add_page'),
)

tango_with_django_project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

from rango import views

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'tango_with_django_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^rango/', include('rango.urls', namespace='rango')),
    url(r'^admin/', include(admin.site.urls)),
)


if settings.DEBUG:
    urlpatterns += patterns('django.views.static',
        (r'media/(?P<path>.*)','serve',{'document_root': settings.MEDIA_ROOT}),
    )

rango/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)

    class Meta:
        verbose_name_plural = 'Categories'

    def __unicode__(self):
        return self.name


class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __unicode__(self):
        return self.title


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_image', blank=True)

    def __unicode__(self):
        return self.user.username

rango/forms.py
from django import forms
from django.contrib.auth.models import User
from rango.models import Page, Category, UserProfile


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Category


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200, help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        #hide forign key 'category'
        fields = ('title', 'url', 'views')

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')
        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url
        return cleaned_data


class UserForm(forms.ModelForm):
    username = forms.CharField(help_text="Please enter a username")
    email = forms.EmailField(help_text="Please enter your email.")
    password = forms.CharField(widget=forms.PasswordInput(), help_text="Please enter a password.")

    class Meta:
        model = User
        fields = ('username', 'email', 'password')
        

class UserProfileForm(forms.ModelForm):
    website = forms.URLField(help_text="Please enter your website.", required=False)
    picture = forms.ImageField(help_text="Select a profile image to upload.", required=False)

    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

rango/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login, logout

from rango.bing_search import run_query
from rango.models import Category, Page
from rango.forms import CategoryForm, PageForm, UserForm, UserProfileForm

from datetime import datetime
# Create your views here.


def index(request):
    page_list = Page.objects.order_by('-views')[:5]

    context_dict = {'categories': get_category_list(), 'pages': page_list}
    if request.session.get('last_visit'):
        last_visit = request.session.get('last_visit')
        visits = request.session.get('visits')
        if (datetime.now() - datetime.strptime(last_visit[:-7], "%Y-%m-%d %H:%M:%S")).seconds > 30:
            request.session['visits'] = visits + 1
            request.session['last_visit'] = str(datetime.now())
    else:
        visits = 1
        request.session['last_visit'] = str(datetime.now())
        request.session['visits'] = 1
    context_dict['visits'] = visits
    return render(request, 'rango/index.html', context_dict)


def about(request):
    if request.session.get('visits'):
        visits = request.session.get('visits')
    return render(request, 'rango/about.html', {'visits': visits})


def category(request, category_name_url):
    category_name = _url_to_name(category_name_url)
    context_dict = {'category_name': category_name,
                    'category_name_url': category_name_url}
    try:
        category = Category.objects.get(name=category_name)
        pages = category.page_set.all()
        context_dict['pages'] = pages
        context_dict['category'] = category
    except Category.DoesNotExist:
        pass
    return render(request, 'rango/category.html', context_dict)


def add_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return HttpResponseRedirect(reverse('rango:index'))
        else:
            print form.errors
    else:
        form = CategoryForm()
    return render(request, 'rango/add_category.html', {'form': form})


def add_page(request, category_name_url):
    category_name = _url_to_name(category_name_url)
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            page = form.save(commit=False)
            category = Category.objects.get(name=category_name)
            page.category = category
            page.save()
            return HttpResponseRedirect(reverse('rango:category', args=(category_name_url,)))
        else:
            print form.errors
    else:
        form = PageForm()
    return render(request, 'rango/add_page.html',
                  {'category_name_url': category_name_url,
                   'category_name': category_name,
                   'form': form})


def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            #hash the password
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            profile.save()
            registered = True
        else:
            print user_form.errors, profile_form.errors
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
    return render(request, 'rango/register.html',
                  {'user_form': user_form,
                   'profile_form': profile_form,
                   'registered': registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('rango:index'))
            return HttpResponse('disabled')
        print 'invalid login detail {0} {1}'.format(username, password)
        return render(request, 'rango/login.html', {'username': username})
    return render(request, 'rango/login.html')


@login_required
def restricted(request):
    return render(request, 'rango/restricted.html')


def search(request):
    result_list = []
    if request.method == 'POST':
        query = request.POST['query'].strip()
        if query:
            result_list = run_query(query)
    return render(request, 'rango/category.html', {'result_list': result_list})


def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('rango:index'))


def get_category_list():
    category_list = Category.objects.order_by('-likes')[:5]

    for category in category_list:
        category.url = _name_to_url(category.name)
    return category_list


def _url_to_name(category_name_url):
    return category_name_url.replace('_', ' ')


def _name_to_url(category_name):
    return category_name.replace(' ', '_')

rango/templates/rango/about.html
{% extends 'rango/base.html' %}
{% block title %} About {% endblock %}
{% load staticfiles %}

{% block body_block %}
<div class="hero-unit">
    <h1>About Rango</h1>
    This is <strong>Rango's about page</strong>.<br />

    You've visited the site on <strong>{{ visits }}</strong> time{{ visits|pluralize }}.<br />

    Here's a picture of Rango!<br />
    <img src="{% static 'img/pics.jpg' %}" alt="Picture of Rango" />
</div>
{% endblock %}

rango/templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% block title %} Add a category {% endblock %}

{% block body_block %}
<div class="hero-unit">
    <h1>Add a category</h1>
    <div class="container">
        <form class="span6" id="category_form" method="post" action="{% url 'rango:add_category' %}">
            {% csrf_token %}
            {% for hidden_field in form.hidden_fields %}
                {{ hidden_field }}
            {% endfor %}
            {% for visible_field in form.visible_fields %}
                {{ visible_field.errors }}
                {{ visible_field.help_text }}<br>
                {{ visible_field }}
            {% endfor %}
            <button class="btn btn-primary" type="submit" name="submit">Create Category</button>
        </form>
    </div>
</div>
{% endblock %}

rango/templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% block title %} Add new Page to {{ category_name }} {% endblock %}

{% block body_block %}
<div class="hero-unit">
    <h1>Add a new page to {{ category_name }}</h1>
    <div class="container">
    <form class="span6" id="page_form" method="post" action="{% url 'rango:add_page' category_name_url %}">
        {% csrf_token %}
        {% for hidden_field in form.hidden_fields %}
            {{ hidden_field }}
        {% endfor %}
        {% for visible_field in form.visible_fields %}
            {{ visible_field.errors }}
            {{ visible_field.help_text }}
            {{ visible_field }}
            <br>
        {% endfor %}
         <button class="btn btn-primary" type="submit" name="submit">Create Category</button>
    </form>
    </div>
</div>
{% endblock %}

rango/templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load category_tag %}
<html>
<head>
    <title>Rango - {% block title %}How to Tango with Django! {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/bootstrap-fluid-adj.css' %}"/>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="brand" href="{% url 'rango:index' %}">Rango</a>

            <div class="nav-collapse collapse">
                <ul class="nav pull-right">
                    {% if user.is_authenticated %}
                        <li class="navbar-text">Welcome, {{ user.username }}</li>
                        <li><a href="{% url 'rango:logout' %}">Logout</a></li>
                    {% else %}
                        <li><a href="{% url 'rango:register' %}">Register</a></li>
                        <li><a href="{% url 'rango:login' %}">Login</a></li>
                    {% endif %}
                </ul>
                <ul class="nav">
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'rango:restricted' %}">Restricted</a></li>
                        <li><a href="{% url 'rango:add_category' %}">Add Category</a></li>
                    {% endif %}
                    <li><a href="{% url 'rango:about' %}">About</a></li>
                </ul>
            </div>


        </div>
    </div>
</div>
<!-- navbar -->

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span3">
            <div class="well sidebar-nav">
                {% category %}
            </div>
        </div>
        <div class="span9">
            {% block body_block %} {% endblock %}
        </div>
    </div>
</div>

<footer>
    <div class="container">
        <p>&copy; Rango: How To Tango with Django 2013</p>
    </div>
</footer>

<script type="text/javascript" src="{% static 'js/jquery-2.0.0.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

rango/templates/rango/category.html
{% extends 'rango/base.html' %}
{% block title %} {{ category_name }} {% endblock %}

{% block body_block %}
    <div class="hero-unit">
        <div class="container">
            <h1>{{ category_name }}</h1>
            {% if category %}
                {% if pages %}
                    <ul>
                        {% for page in pages %}
                            <li><a href="{{ page.url }}">{{ page.title }}</a></li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <strong>No pages currently in category.</strong>
                {% endif %}
            {% else %}
                The specified category {{ category_name }} does not exist!
            {% endif %}
            {% if user.is_authenticated %}
                <a class="pull-right" href="{% url 'rango:add_page' category_name_url %}">Add a new page</a>
            {% endif %}
        </div>
    </div>
{% endblock %}

rango/templates/rango/category_list.html
<h2>Top Five Categories</h2>
{% if categories %}
    <ul>
        {% for category in categories %}
            <li><a href="{% url 'rango:category' category.url %}">{{ category.name }}</a>
                - ({{ category.likes }} like{{ category.likes|pluralize }})
            </li>
        {% endfor %}
    </ul>
{% else %}
    <strong>No categories at present.</strong>
{% endif %}
{% include 'rango/search.html' %}

rango/templates/rango/index.html
{% extends 'rango/base.html' %}

{% block body_block %}
    <div class="hero-unit">
        <h1>Ready to Rango</h1>

        <p>Find, Add, Share and Rango useful links and resources.</p>
    </div>

    <div class="row-fluid">
        <div class="span6">
            {% include 'rango/category_list.html' %}
        </div>
        <div class="span6">
            <h2>Top Five Pages</h2>
            {% if pages %}
                <ul>
                    {% for page in pages %}
                        <li><a href="{{ page.url }}">{{ page.title }}</a>
                            - {{ page.category }}({{ page.views }} view{{ page.views|pluralize }})</li>
                    {% endfor %}
                </ul>
            {% else %}
                <strong>No pages at present.</strong>
            {% endif %}
        </div>
    </div>
{% endblock %}

rango/templates/rango/login.html
{% extends 'rango/base.html' %}
{% block title %} Login {% endblock %}

{% block body_block %}
    <div class="hero-unit">
        <h1>Login to Rango</h1>
        <div class="container">


            <form class="span4" id="login_form" method="post" action="{% url 'rango:login' %}">

                <h2 class="form-signin-heading">Please sign in</h2>
                {% csrf_token %}
                {% if bad_details %}
                    <p><strong>Your username and/or password were incorrect!</strong></p>
                {% elif disabled_account %}
                    <p><strong>Your Rango account is currently disabled; we can't log you in!</strong></p>
                {% endif %}
                Username: <input class="input-block-level" placeholder="Username" type="text" name="username"
                                 value="{{ username }}" size="50"/><br>
                Password: <input class="input-block-level" placeholder="Password" type="password" name="password"
                                 value="" size="50"/><br>
                <button class="btn btn-primary" type="submit">Sign in</button>
            </form>
        </div>
    </div>
{% endblock %}

rango/templates/rango/register.html
{% extends 'rango/base.html' %}
{% block title %} Register {% endblock %}

{% block body_block %}
    <div class="hero-unit">
        <h1>Register with Rango</h1>
        <br>

        <div class="container">
            {% if registered %}
                <p>Rango says: <strong>thank you for registering!</strong></p>
                <p><a href="{% url 'rango:login' %}">Login</a> when you're ready</p>
            {% else %}
                <form class="form-signin span8" id="user_form" action="{% url 'rango:register' %}"
                      enctype="multipart/form-data" method="post">
                    {% csrf_token %}
                    <h2 class="form-signin-heading">Sign up here</h2>
                    {% for field in user_form.visible_fields %}
                        {{ field.errors }}
                        {{ field.help_text }}<br/>
                        {{ field }}<br/>
                    {% endfor %}

                    {% for field in profile_form.visible_fields %}
                        {{ field.errors }}
                        {{ field.help_text }}<br/>
                        {{ field }}<br/>
                    {% endfor %}
                    <br/>
                    <!-- Provide a button to click to submit the form. -->
                    <input class="btn btn-primary" type="submit" name="submit" value="Register"/>
                </form>
            {% endif %}
        </div>
    </div>
{% endblock %}

rango/templates/rango/restricted.html
{% extends 'rango/base.html' %}
{% block title %} Restricted {% endblock %}

{% block body_block %}
    <div class="hero-unit">
        <div class="container">
            <p>"Since you're logged in, you can see this text!"</p>
        </div>
    </div>

{% endblock %}

rango/templates/rango/search.html
<div class="container-fluid">
    <form class="span8" id="user_form" method="post" action="{% url 'rango:search' %}">
        {% csrf_token %}
        <input type="text" name="query" id="query" value="" size="50"/>
        <input class="btn btn-primary" type="submit" name="submit" value="Search"/>
        <br>
    </form>
    {% if result_list %}
        <div style="clear: both;">
            <ol>
                {% for result in result_list %}
                    <li>
                        <strong><a href="{{ result.link }}">{{ result.title }}</a></strong>
                        <em>{{ result.summary }}</em>
                    </li>
                {% endfor %}
            </ol>
        </div>
    {% endif %}
</div>